"""create_initial_models

Revision ID: 3f9399d049cb
Revises: 
Create Date: 2026-09-09 14:43:39.106213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '3f9399d049cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_status'), 'bots', ['status'], unique=False)
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=False)
    op.create_table('brand_settings',
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('favicon_url', sa.String(length=2048), nullable=True),
    sa.Column('primary_color', sa.String(length=32), nullable=True),
    sa.Column('secondary_color', sa.String(length=32), nullable=True),
    sa.Column('background_color', sa.String(length=32), nullable=True),
    sa.Column('text_color', sa.String(length=32), nullable=True),
    sa.Column('font_family', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_bot_id'), 'conversations', ['bot_id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('processed_pages', sa.Integer(), nullable=False),
    sa.Column('failed_pages', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_bot_id'), 'crawl_jobs', ['bot_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('crawl_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_bot_id'), 'pages', ['bot_id'], unique=False)
    op.create_index(op.f('ix_pages_content_hash'), 'pages', ['content_hash'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('storage_url', sa.String(length=2048), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_bot_id'), 'assets', ['bot_id'], unique=False)
    op.create_index(op.f('ix_assets_page_id'), 'assets', ['page_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_bot_id'), 'chunks', ['bot_id'], unique=False)
    op.create_index(op.f('ix_chunks_page_id'), 'chunks', ['page_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_bot_id'), 'documents', ['bot_id'], unique=False)
    op.create_index(op.f('ix_documents_page_id'), 'documents', ['page_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_documents_page_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_bot_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chunks_page_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_bot_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_assets_page_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_bot_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_pages_content_hash'), table_name='pages')
    op.drop_index(op.f('ix_pages_bot_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_bot_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_bot_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('brand_settings')
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_status'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
