"""add_hubspot_oauth_to_users

Revision ID: c2296287231a
Revises: 3dca83d98212
Create Date: 2026-09-10 21:25:05.126122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2296287231a'
down_revision: Union[str, Sequence[str], None] = '3dca83d98212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hubspot_access_token', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('hubspot_refresh_token', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('hubspot_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('hubspot_portal_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('hubspot_connected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hubspot_connected_at')
    op.drop_column('users', 'hubspot_portal_id')
    op.drop_column('users', 'hubspot_token_expires_at')
    op.drop_column('users', 'hubspot_refresh_token')
    op.drop_column('users', 'hubspot_access_token')
    # ### end Alembic commands ###
